### ISSUE TITLE
Can't install it.

### ISSUE THREAD

**Issue by ryc16** [laixiangran/e-ngx-print#1]
I just downloaded it and give it a try. I typed "npm install" to install the dependency but I got failed. See below. Please advice.

```
>npm install

> essence-ng2-print@1.0.7 prepublish C:\codeprojs\angular\#printing\essence-ng2-print
> gulp prepublish && ngc

[14:32:45] Using gulpfile C:\codeprojs\angular\#printing\essence-ng2-print\gulpfile.js
[14:32:45] Starting 'prepublish'...
[14:32:45] Starting 'clean:dist'...
[14:32:45] Finished 'clean:dist' after 4.59 ms
[14:32:45] Starting 'copy:src'...
[14:32:45] Finished 'copy:src' after 48 ms
[14:32:45] Starting 'ng2:inline'...
[14:32:45] Finished 'ng2:inline' after 192 ms
[14:32:45] Finished 'prepublish' after 255 ms
Error at C:/codeprojs/angular/#printing/essence-ng2-print/node_modules/@types/jquery/index.d.ts:28:39: Generic type 'JQueryStatic<TElement, HTMLElement>' requires 2 type argument(s).
Error at C:/codeprojs/angular/#printing/essence-ng2-print/node_modules/@types/jquery/index.d.ts:28:54: Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).
Error at C:/codeprojs/angular/#printing/essence-ng2-print/node_modules/@types/jquery/index.d.ts:30:45: Generic type 'JQueryStatic<TElement, HTMLElement>' requires 2 type argument(s).
Error at C:/codeprojs/angular/#printing/essence-ng2-print/node_modules/@types/jquery/index.d.ts:35:39: Generic type 'JQueryStatic<TElement, HTMLElement>' requires 2 type argument(s).
Error at C:/codeprojs/angular/#printing/essence-ng2-print/node_modules/@types/jquery/index.d.ts:35:54: Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).
Error at C:/codeprojs/angular/#printing/essence-ng2-print/node_modules/@types/jquery/index.d.ts:37:45: Generic type 'JQueryStatic<TElement, HTMLElement>' requires 2 type argument(s).
```

**Comment by laixiangran** [comment]
This is a problem. running  gulp prepublish && ngc before running the  npm install. I has modify it.
